### ISSUE TITLE
Shorten Naming convention

### ISSUE THREAD

**Issue by bjoshuanoah** [Wolfram-Creative/fractional#2]
Currently we have 'five_eighths columns' I'm thinking something like 'f5_7' or 'f1-4' or 'f5o7'

**Comment by bjoshuanoah** [comment]
_1-5

**Comment by bjoshuanoah** [comment]
##default
f5-7
###small:
s5-7
###medium
m5-7
###medium large
ml5-7

**Comment by bjoshuanoah** [comment]
@etanlubeck @jcblw what do you think?

**Comment by etanlubeck** [comment]
I like it. I think there should be some sort of contextual prefix identifier in the name without having to have a complementary class name. So something like: .c-ml5-7

**Comment by bjoshuanoah** [comment]
I'm trying to get away from column, but I like your idea
####default
f5-7

####small:
f5-7s

####medium
f5-7m

####medium large
f5-7ml

**Comment by bjoshuanoah** [comment]
f denoting fraction

**Comment by bjoshuanoah** [comment]
After doing some more research, I found that we can include "/" in a class name. The only thing is that you have to use "\2F ". I didn't want to do this at first, then I remembered that this will only be in the css code that isn't touched, and will be used as stated, with a slash.

f5/7
f5/7s
f5/lm
f5/7ml
